version: '3.0'

services:

  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - configdb:/data/configdb
    networks:
      - myscrapingapp-network

  mongoexpress:
    image: mongo-express
    container_name: mongoexpress
    restart: always
    ports:
      - 8081:8081
    networks:
      - myscrapingapp-network
    depends_on:
      - mongodb

  mypyapp:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: mypyapp
    volumes:
      - "./app:/var/www/app"
    ports:
      - 5000:5000
    networks:
      - myscrapingapp-network
    depends_on:
      - mongodb


networks:
    myscrapingapp-network:
        driver: bridge

volumes:
    mongodb:
    configdb: